name: Build and push docker server image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [released]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.repository == 'surrealtm/Glassminers' && (github.event_name == 'push' || github.event_name == 'release')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            surrealtm/glassminers-server
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
            type=raw,value={{version}},enable=${{ github.event_name == 'release' }}
            type=sha,enable=${{ github.event_name == 'push' }}
            type=raw,value=nightly,enable=${{ github.event_name == 'push' }}
          flavor: |
            latest=false
            prefix=
            suffix=

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
