name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Run on releases AND on pushes to main
    if: |
      (github.event_name == 'release' && github.event.action == 'published') ||
      github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get full git history for metadata action

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            surrealtm/glassminers-server
          tags: |
            # For releases
            type=raw,value=latest
            type=raw,value={{version}}
            # For commits to main
            type=sha
            type=raw,value=nightly
          flavor: |
            latest=false
            prefix=
            suffix=
            ${{ github.event_name == 'push' && 'nightly=true' || 'nightly=false' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
